### ISSUE TITLE
errors searching for references

### ISSUE THREAD

**Issue by cjrood** [pywbem/pywbemtools#806] opened 2020-10-14 21:31 UTC
Might be a bit hard to reproduce, but maybe you can determine the issue from the stack trace. If I issue the following cmd it crashes with an error. It may be that there is somethin wrong with the classes but it should recover more gracefully. Its a brand new provider that I am developing still. I can provide more logs or associated output too. Maybe I will output the array and some other references as well.

c:\bld\smi-s-pegasus-1_x\build\smis_query>pywbemcli --server  http://172.17.170.1:5988  --no-verify -u xyz -p xyz   instance  references IFA_Array.? -n Intelliflash
Traceback (most recent call last):
  File "c:\tools\python\385\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\tools\python\385\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\tools\python\385\Scripts\pywbemcli.exe\__main__.py", line 7, in <module>
  File "c:\tools\python\385\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "c:\tools\python\385\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "c:\tools\python\385\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\tools\python\385\lib\site-packages\click\core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\tools\python\385\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\tools\python\385\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "c:\tools\python\385\lib\site-packages\click\decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "c:\tools\python\385\lib\site-packages\pywbemtools\pywbemcli\_cmd_instance.py", line 480, in instance_references
    context.execute_cmd(lambda: cmd_instance_references(context, instancename,
  File "c:\tools\python\385\lib\site-packages\pywbemtools\pywbemcli\_context_obj.py", line 286, in execute_cmd
    cmd()
  File "c:\tools\python\385\lib\site-packages\pywbemtools\pywbemcli\_cmd_instance.py", line 480, in <lambda>
    context.execute_cmd(lambda: cmd_instance_references(context, instancename,
  File "c:\tools\python\385\lib\site-packages\pywbemtools\pywbemcli\_cmd_instance.py", line 1202, in cmd_instance_references
    results = context.conn.PyWbemcliReferenceInstances(
  File "c:\tools\python\385\lib\site-packages\pywbemtools\pywbemcli\_pywbemcli_operations.py", line 189, in PyWbemcliReferenceInstances
    return list(result)
  File "c:\tools\python\385\lib\site-packages\pywbem\_cim_operations.py", line 5899, in IterReferenceInstances
    enum_rslt = self.References(
  File "c:\tools\python\385\lib\site-packages\pywbem\_cim_operations.py", line 3941, in References
    result = self._imethodcall(
  File "c:\tools\python\385\lib\site-packages\pywbem\_cim_operations.py", line 1769, in _imethodcall
    tup_tree = tp.parse_cim(tt_)
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 408, in parse_cim
    child = self.one_child(tup_tree, ('MESSAGE', 'DECLARATION'))
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 282, in one_child
    return self.parse_any(child)
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 2091, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 1652, in parse_message
    child = self.one_child(tup_tree,
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 282, in one_child
    return self.parse_any(child)
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 2091, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 1807, in parse_simplersp
    child = self.one_child(tup_tree, ('METHODRESPONSE', 'IMETHODRESPONSE'))
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 282, in one_child
    return self.parse_any(child)
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 2091, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 1865, in parse_imethodresponse
    self.list_of_various(tup_tree,
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 322, in list_of_various
    result.append(self.parse_any(child))
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 2091, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 1944, in parse_ireturnvalue
    values = self.list_of_same(tup_tree,
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 371, in list_of_same
    result.append(self.parse_any(child))
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 2091, in parse_any
    return func(tup_tree)  # a bound method, i.e. self is implicit
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 707, in parse_value_objectwithpath
    inst_path = self.parse_instancepath(k[0])
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 912, in parse_instancepath
    inst_path = self.parse_instancename(k[1])
  File "c:\tools\python\385\lib\site-packages\pywbem\_tupleparse.py", line 991, in parse_instancename
    return CIMInstanceName(classname, kbs)
  File "c:\tools\python\385\lib\site-packages\pywbem\_cim_obj.py", line 1176, in __init__
    self.keybindings = keybindings
  File "c:\tools\python\385\lib\site-packages\pywbem\_cim_obj.py", line 1303, in keybindings
    self.keybindings[key] = _cim_keybinding(key, value)
  File "c:\tools\python\385\lib\site-packages\pywbem\_cim_obj.py", line 959, in _cim_keybinding
    raise TypeError(
TypeError: Value of keybinding 'SameElement' has an invalid type: <class 'pywbem._cim_obj.CIMClassName'>

c:\bld\smi-s-pegasus-1_x\build\smis_query>

**Comment by andy-maier** [comment] 2020-10-15 06:42
Hi.
I agree the error handling could be more graceful.

We need some more information to track this down:
- Which version of pywbemtools and pywbem are you using? (run `pywbemcli --version`)
- The response seems to contain an instance with an instance name that has an invalid type for a keybinding. Please provide the CIM-XML of the response. You can do that by adding the option `--log http` and posting the log file `pywbem.log` (the one log entry for the References response is sufficient).
- I suppose the type of the "SameElement" property in the result class is a reference. Please confirm that, tell us which class it references, and provide the definition of the key properties of the referenced class (for example in MOF).

**Comment by andy-maier** [comment] 2020-10-21 15:53
I created https://github.com/pywbem/pywbem/issues/2512 for improving the error handling when getting invalid CIM-XML responses from the server.

**Comment by KSchopmeyer** [comment] 2020-10-21 16:15
Chris, if you can send a pegasus trace involving this request/response and also one that suceeds.  Also, try this with cimcli to see if he accepts it since the client response parser is completely different.

**Comment by cjrood** [comment] 2020-10-22 18:26
here is the logs i hope this helps
[bug.zip](https://github.com/pywbem/pywbemtools/files/5424893/bug.zip)
let me know if it didnt transfer or something

**Comment by KSchopmeyer** [comment] 2020-10-23 17:22
I beieve he issue is coming from the response at either line 659 or 711 where an element  LOCALCLASSPATH is being returned

              <VALUE.OBJECTWITHPATH>
                <INSTANCEPATH>
                  <NAMESPACEPATH>
                    <HOST>hv192-cjrW12smis</HOST>
                    <LOCALNAMESPACEPATH>
                      <NAMESPACE NAME="Intelliflash" />
                    </LOCALNAMESPACEPATH>
                  </NAMESPACEPATH>
                  <INSTANCENAME CLASSNAME="IFA_McsRedundancySetIdentity">
                    <KEYBINDING NAME="SameElement">
                      <VALUE.REFERENCE>
                        <LOCALCLASSPATH>
                          <LOCALNAMESPACEPATH>
                            <NAMESPACE NAME="Intelliflash" />
                          </LOCALNAMESPACEPATH>
                          <CLASSNAME NAME="IFA_McsControllerRedundancySet" />
                        </LOCALCLASSPATH>
                      </VALUE.REFERENCE>
                    </KEYBINDING>
                    <KEYBINDING NAME="SystemElement">
                      <VALUE.REFERENCE>
                        <LOCALINSTANCEPATH>
                          <LOCALNAMESPACEPATH>
                            <NAMESPACE NAME="Intelliflash" />
                          </LOCALNAMESPACEPATH>
                          <INSTANCENAME CLASSNAME="IFA_Array">
                            <KEYBINDING NAME="CreationClassName">
                              <KEYVALUE VALUETYPE="string">IFA_Array</KEYVALUE>
                            </KEYBINDING>
                            <KEYBINDING NAME="Name">
                              <KEYVALUE VALUETYPE="string">172.18.76.227</KEYVALUE>
                            </KEYBINDING>
                          </INSTANCENAME>
                        </LOCALINSTANCEPATH>
                      </VALUE.REFERENCE>
                    </KEYBINDING>
                  </INSTANCENAME>
                </INSTANCEPATH>
                <INSTANCE CLASSNAME="IFA_McsRedundancySetIdentity">
                  <PROPERTY.REFERENCE NAME="SystemElement">
                    <VALUE.REFERENCE>
                      <LOCALINSTANCEPATH>
                        <LOCALNAMESPACEPATH>
                          <NAMESPACE NAME="Intelliflash" />
                        </LOCALNAMESPACEPATH>
                        <INSTANCENAME CLASSNAME="IFA_Array">
                          <KEYBINDING NAME="CreationClassName">
                            <KEYVALUE VALUETYPE="string">IFA_Array</KEYVALUE>
                          </KEYBINDING>
                          <KEYBINDING NAME="Name">
                            <KEYVALUE VALUETYPE="string">172.18.76.227</KEYVALUE>
                          </KEYBINDING>
                        </INSTANCENAME>
                      </LOCALINSTANCEPATH>
                    </VALUE.REFERENCE>
                  </PROPERTY.REFERENCE>
                  <PROPERTY.REFERENCE NAME="SameElement">
                    <VALUE.REFERENCE>
                      <LOCALCLASSPATH>
                        <LOCALNAMESPACEPATH>
                          <NAMESPACE NAME="Intelliflash" />
                        </LOCALNAMESPACEPATH>
                        <CLASSNAME NAME="IFA_McsControllerRedundancySet" />
                      </LOCALCLASSPATH>
                    </VALUE.REFERENCE>
                  </PROPERTY.REFERENCE>
                </INSTANCE>
              </VALUE.OBJECTWITHPATH>

**Comment by KSchopmeyer** [comment] 2020-10-23 17:55
Andy, I created a functiontest to  catch the problem and it is compressed into this zip file.  I put this into functiontests and just ran make test TESTCASES=chris.  Caught the issue and this is a duplicatable test. 

[functiontest.zip](https://github.com/pywbem/pywbemtools/files/5430982/functiontest.zip)

Right now it looks like we are not considering ClassPath (or in this case LOCALCLASSPATH) as a valid VALUE.REFERENCE type in a KEYBINDING but it is allowed in accord with DSP0201 (see section 5.3.3.3). However, I may be missing something here.

                  <INSTANCENAME CLASSNAME="IFA_McsRedundancySetIdentity">
                    <KEYBINDING NAME="SameElement">
                      <VALUE.REFERENCE>
                        <LOCALCLASSPATH>
                          <LOCALNAMESPACEPATH>
                            <NAMESPACE NAME="Intelliflash" />
                          </LOCALNAMESPACEPATH>
                          <CLASSNAME NAME="IFA_McsControllerRedundancySet" />
                        </LOCALCLASSPATH>
                      </VALUE.REFERENCE>
                    </KEYBINDING>
                    <KEYBINDING NAME="SystemElement">
                      <VALUE.REFERENCE>
                        <LOCALINSTANCEPATH>
                          <LOCALNAMESPACEPATH>
                            <NAMESPACE NAME="Intelliflash" />
                          </LOCALNAMESPACEPATH>
                          <INSTANCENAME CLASSNAME="IFA_Array">
                            <KEYBINDING NAME="CreationClassName">
                              <KEYVALUE VALUETYPE="string">IFA_Array</KEYVALUE>
                            </KEYBINDING>
                            <KEYBINDING NAME="Name">
                              <KEYVALUE VALUETYPE="string">172.18.76.227</KEYVALUE>
                            </KEYBINDING>
                          </INSTANCENAME>
                        </LOCALINSTANCEPATH>
                      </VALUE.REFERENCE>
                    </KEYBINDING>
                  </INSTANCENAME>

**Comment by KSchopmeyer** [comment] 2020-10-23 18:45
It get the original exception from CIMInstanceNmae.__init__() on the line

self.keybindings = keybindings

where keybindings is:

{'SameElement': CIMClassName(classname='IFA_McsControllerRedundancySet', namespace='Intelliflash', host=None), 'SystemElement': CIMInstanceName(classname='IFA_Array', keybindings=NocaseDict({'CreationClassName': 'IFA_Array', 'Name': '172.18.76.227'}), namespace='Intelliflash', host=None)}

**Comment by andy-maier** [comment] 2020-10-24 04:13
Here is the standards perspective:
* I double checked DSP0201 2.4.0 and indeed it allows for LOCALCLASSPATH being a child element of VALUE.REFERENCE.
* Then I double checked DSP0004 2.8.0, and in 7.7.5 "Object References", it says: "Object references in associations shall reference instances only and shall not have the special Null value.". That disallows class paths in references used in associations. Class paths may be used in method parameters that are references, although that has been deprecated a few lines below the quoted text.

It does not make any sense for a reference in an association to reference a class, and it is disallowed as per DSP0004. I suggest opening a bug against the implementation that returns this.

Having said this, we should deal with this situation in a pragmatic way, and that is by tolerating this case (just as cimcli apparently does). I have created issue https://github.com/pywbem/pywbem/issues/2514 to do that in pywbem.

**Comment by andy-maier** [comment] 2020-10-24 10:15
PR #2515 has been created that adds toleration for class paths in references of association instances. Still needs to be completed with unit tests, and then rolled back to pywbem 1.1.

**Comment by cjrood** [comment] 2020-10-24 21:42
thanks so much andy and karl for lookin at this, and your help, I did find an issue on my side yesterday night. there was an empty instance id, in McsControllerRedundancySet. So your code really detected a missing piece in my code. I do still see stack trace exceptions, but those are not critical or aren't missing functionality.
![bug_error_code](https://user-images.githubusercontent.com/61169695/97094075-4220e900-1606-11eb-92fb-02ebbc628929.png)
[pywbem_enumIfa_mcsarray_out.txt](https://github.com/pywbem/pywbemtools/files/5433812/pywbem_enumIfa_mcsarray_out.txt)

**Comment by andy-maier** [comment] 2020-10-27 08:20
Hi Chris, that is good to hear.
BTW, it also helped our code:
* Pywbem PR https://github.com/pywbem/pywbem/pull/2516 will improve how such cases are surfaced and will better allow us to understand the situation without having to ask for reproduction and logs.
* Since OpenPegasus did return the missing InstanceID as a class path, Karl will look at how that happens in OP, and pywbem will also add some toleration support for this case, the details of which we are still discussing.

**Comment by andy-maier** [comment] 2020-10-31 22:00
Hi Chris @cjrood 
We have released pywbem 1.1.2 with exception handling improvements. Using this version should cause pywbemcli in your scenario with the instance references command to display a proper error message instead of a Python traceback. The returned class path is still an issue on the server side. We cannot tolerate or fix that on the client side.

**Comment by andy-maier** [comment] 2020-10-31 22:02
I am closing this issue because other than improving the error reporting as explained in the previous comment, there is nothing we can do on the client side.

**Closed by andy-maier** 2020-10-31 22:02 UTC
Labels: area: code, release: user generated, resolution: pursued in different issues
