### ISSUE TITLE
Change help to show command options after command arguments

### ISSUE THREAD

**Issue by FarmerMike252** [pywbem/pywbemtools#446] opened 2019-10-18 13:40 UTC
I recommend changing the help for commands to show command options after command arguments. When you make an error in the command options the error message is more informative.

See the example below:
```
pywbemcli> instance enumerate --pl StatisticTime,TotalIOs, KBytesTransferred CIM_BlockStorageStatisticalData
Usage: pywbemcli  instance enumerate [COMMAND-OPTIONS] CLASSNAME
Try "pywbemcli  instance enumerate -h" for help.

Error: Got unexpected extra argument (CIM_BlockStorageStatisticalData)
```

```
pywbemcli> instance enumerate CIM_BlockStorageStatisticalData --pl StatisticTime,TotalIOs, KBytesTransferred
Usage: pywbemcli  instance enumerate [COMMAND-OPTIONS] CLASSNAME
Try "pywbemcli  instance enumerate -h" for help.

Error: Got unexpected extra argument (KBytesTransferred)
```

The usage help should read:
```
Usage: pywbemcli  instance enumerate CLASSNAME [COMMAND-OPTIONS]
```

**Comment by andy-maier** [comment] 2019-10-25 14:51
Karl believe it is actually possible to set the help string. If that is possible, the help string should also show `[GLOBAL-OPTIONS]` after the command name.

**Comment by KSchopmeyer** [comment] 2019-11-01 13:54
The command group args after the command name is logical.  However, I believe that showing the GLOBAL_OPTIONS after the command is not possible.  Note also that it turns out we do not have as much control of this config line as I thought without subclassing click buth by subclassing we get almost total control.

Today the three levels of usage line are as follows:

'''

  Global Usage line:  
   pywbemcli -h 
   Usage: pywbemcli [GENERAL-OPTIONS] COMMAND [ARGS]...

    pywbemcli class -h
    Usage: pywbemcli class [COMMAND-OPTIONS] COMMAND [ARGS]..

    pywbemcli class get -h
    Usage: pywbemcli class get [COMMAND-OPTIONS] CLASSNAME

**Comment by andy-maier** [comment] 2020-03-17 07:56
I agree with the proposal to also show the `[GENERAL-OPTIONS]`.

**Comment by andy-maier** [comment] 2020-03-31 07:29
Fixed in PR #560

**Comment by andy-maier** [comment] 2020-04-01 07:02
I'm reopening this issue to discuss the discussion point that came up during review of PR #560:

We currently have a section heading "Options:" in the help text. With both GENERAL-OPTIONS and CMD-OPTIONS in the usage line, it is now ambiguous as to whether that section lists the GENERAL-OPTIONS or the CMD-OPTIONS.

I see three options how to go about this:
* Best option would be to change the section heading text to "General options:" for the top level help, and to "Command options:" for the lower level help.
* Next best option would be to change the meta variables in the usage line so that the options shown in the "Options:" section are always named OPTIONS, which would be the general options for the top level help and the command options for the lower level help. The other options would keep their current name.
* Of course, we can also declare the problem is addressed well enough and do nothing.

**Comment by KSchopmeyer** [comment] 2020-04-02 09:03
The first Option is the obvious choice. But since click did not conceive of  the two types in the usage statement, I need to be certain we can make this safely work with monkey patching.

**Comment by andy-maier** [comment] 2020-04-02 19:11
The latest update to the PR nicely implements the first option. Let's agree on the remaining discussion point on CMD-OPTION vs COMMAND-OPTION, in the PR.

**Closed** 2020-04-03 21:43 UTC
Labels: area: code, release: mandatory, release: user generated, resolution: fixed
