### ISSUE TITLE
tests on windows platform fail 

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#824] opened 2020-12-16 15:45 UTC
The tests on the windows platfroms have started failing early in the build with the following output:

Run make build
del /f /q pip_upgrade_py3.8.done
Could Not Find D:\a\pywbemtools\pywbemtools\pip_upgrade_py3.8.done
python -m pip install -c minimum-constraints.txt pip
DEPRECATION: Constraints are only allowed to take the form of a package name and a version specifier. Other forms were originally permitted as an accident of the implementation, but were undocumented. The new implementation of the resolver no longer supports these forms. A possible replacement is replacing the constraint with a requirement.. You can find discussion regarding this at https://github.com/pypa/pip/issues/8210.
ERROR: Links are not allowed as constraints
WARNING: You are using pip version 20.3.1; however, version 20.3.3 is available.
You should consider upgrading via the 'C:\hostedtoolcache\windows\Python\3.8.6\x64\python.exe -m pip install --upgrade pip' command.
mingw32-make: *** [Makefile:406: pip_upgrade_py3.8.done] Error 1
Error: Process completed with exit code 1.

**Comment by andy-maier** [comment] 2020-12-30 07:07
This is caused by a new version of Pip no longer tolerating github links in the minimum constraints file. This was fixed in PR #825 in master, abd rolled back with PR #826 into 0.8.

**Closed** 2020-12-30 12:53 UTC
Labels: area: devlopment env, resolution: fixed, roll back/forward done, type: bug
