### ISSUE TITLE
Cannot set the default namespace to "interop"

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#991] opened 2021-06-13 16:20 UTC
A command on the mock of multiple namespace with interop (SIMPLE_INTEROP_MOCK_SCRIPT.py) fails when a command that uses the general option -d to set the subcommand default namespace  to interop for that command is execute.

```
   pywbem -m tests/unit/pywbemcli/simple_interop_script.py
   pywbemcli> -d interop class enumerate --ni --do 
```
Note that the command:
```
class enumerate --ni --d  -n interop
```
works
   
**Example of the failure**
```
(pycli39) kschopmeyer@leonard:~/pywbem/pycli39/pywbemtools(ks/#990-invokemethod-ignores-namespace)$ ppp -m tests/unit/pywbemcli/simple_interop_mock_script.py 
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli>
pywbemcli> -d interop class enumerate --no --di
-/home/kschopmeyer/virtualenvs/pycli39/lib/python3.9/site-packages/pywbem/_server.py:523: ToleratedServerIssueWarning: Server at http://FakedUrl:5988 has an Interop namespace 'interop', but does not return it when enumerating class 'CIM_Namespace' - adding it to the 'namespaces' property
  self._determine_namespaces()
Mock script tests/unit/pywbemcli/simple_interop_mock_script.py failed: 3 (CIM_ERR_INVALID_NAMESPACE): Namespace does not exist in CIM repository: 'root/cimv2'
Aborted!
```

**Comment by andy-maier** [comment] 2021-07-17 15:34
This behavior can also be reproduced without using interactive mode:

```
$ pywbemcli -m tests/unit/pywbemcli/simple_interop_mock_script.py -d interop class tree
-/Users/maiera/PycharmProjects/pywbem/pywbem/pywbem/_server.py:523: ToleratedServerIssueWarning: Server at http://FakedUrl:5988 has an Interop namespace 'interop', but does not return it when enumerating class 'CIM_Namespace' - adding it to the 'namespaces' property
  self._determine_namespaces()
Mock script tests/unit/pywbemcli/simple_interop_mock_script.py failed: 3 (CIM_ERR_INVALID_NAMESPACE): Namespace does not exist in CIM repository: 'root/cimv2'
Aborted!
```
The issue does not happen when settng the default namespace to `root/cimv2`:
```
$ pywbemcli -m tests/unit/pywbemcli/simple_interop_mock_script.py -d root/cimv2 class tree
root
 +-- CIM_BaseEmb
 |   +-- CIM_FooEmb1
 |   +-- CIM_FooEmb2
 |   +-- CIM_FooEmb3
 +-- CIM_BaseRef
 |   +-- CIM_FooRef1
 |   +-- CIM_FooRef2
 +-- CIM_Foo
 |   +-- CIM_Foo_sub
 |   |   +-- CIM_Foo_sub_sub
 |   +-- CIM_Foo_sub2
 +-- CIM_FooAssoc
```

**Comment by andy-maier** [comment] 2021-07-19 05:52
The default namespace is an attribute of the connection:
```
$ pywbemcli connection show pegasus
Connection status:
name               value  (state)
-----------------  ----------------------
name               pegasus
server             https://localhost:5989
default-namespace  root/cimv2
user
password
timeout            60
use-pull
pull-max-cnt       1000
verify             False
certfile
keyfile
mock-server
ca-certs
```

The connection is inherited from the parent (the outer cli command) to the child (the inner interactive session).
The question is do we want to allow overriding attributes of the inherited connection.

Proposal: We do not allow such overrides, i.e. the attempt to specify a default namespace in the child if there is an inherited connection, is rejected.

**DISCUSSION**

**Comment by andy-maier** [comment] 2021-08-07 17:38
This issue should be re-evaluated after merging #1036

**Comment by andy-maier** [comment] 2021-08-08 05:10
After having merged PR #1036, the original issue still exists.
The proposal further up to not allow overrides of connection attributes, is moot since with PR #1036, such overrides are now allowed.

So the goal is to properly support an override of the default namespace.

**Comment by andy-maier** [comment] 2021-08-08 05:54
Here is an analysis of what happens:

* The 'simple_interop_mock_script.py' mock script has this basic logic:
  * If the 'interop' namespace does not exist in the mock CIM repository, add it.
  * Compile the main MOF file 'simple_interop_mock_model.mof' into the default namespace of the connection.
* The main MOF file sets namespace pragmas to select the target namespace:
  ```
  #pragma namespace ("interop")
  #pragma include ("mock_interop.mof")
  #pragma namespace ("root/cimv2")
  #pragma include ("simple_mock_model.mof")
  ```
* The MOF compilation does not create namespaces as needed, instead it depends on them to exist.
* The FakedWBEMConnection class creates the default namespace of the connection in its mock repository (in its `cimrepository` property)

**Comment by andy-maier** [comment] 2021-08-08 06:18
I think what needs to happen in any case is to change the mock script to also create namespace "root/cimv2". After all, its main MOF file explicitly depends on that namespace by means of its namespace pragma, so it is only fair to require that the script takes care of that instead of relying on the default namespace not being changed.

However, one possibly unexpected behavior will still be that a different default namespace of a mock connection will cause that namespace to be created, and that behavior will even be inconsistent between global options `-m` plus `-d` (which will create it) and `-n` plus `-d` (which will error out because it does not exist). That brings up the question whether it is a good idea to create an initial namespace using the default namespace of the mock connection.

**Comment by KSchopmeyer** [comment] 2021-11-30 18:25
We agreed that we should try to catch the inconsistency and create an exception that helps the user.

ACTION: Explore.  Karl

**Comment by KSchopmeyer** [comment] 2021-12-02 17:22
In this case, I believe that the issue is with the mock script itself.  It is defined to put data into the INTEROP namespace and the root/cimv2 namespace.  It depends on the root/cimv2 namespace being defined as the default because the script does not provide any means to create this namespace.  So if the user specifies interop as the default, the root/cimv2 namespace never gets created and the mof compile finds a #pragma namespace ("root/cimv2") where that namespace has never been created.

In another test example:

  ppp -d interop -m tests/unit/pywbemcli/testmock/wbemserver_mock_script.py connection show

```

Connection status:
name               value  (state)
-----------------  -------------------------------------------------------
name               not-saved (current)
server
default-namespace  interop
user
password
timeout            30
use-pull
pull-max-cnt       1000
verify             True
certfile
keyfile
mock-server        tests/unit/pywbemcli/testmock/wbemserver_mock_script.py
```

The example works because the script creates both namespaces.

**Comment by KSchopmeyer** [comment] 2021-12-02 17:24
Given that we agree that the use of the namespace mof pragma should not create a namespace, the script itself must create it for the mock environment.

**Comment by KSchopmeyer** [comment] 2021-12-02 17:52
Adding the following to the test script tests/unit/pywbemcli/simple_interop_mock_script.py

```
USER_NAMESPACE = 'root/cimv2'

...

    if USER_NAMESPACE not in conn.cimrepository.namespaces:
            conn.add_namespace(USER_NAMESPACE)

```

Fixes the issue so this script compiles correctly.  This does not mean that this is the correct long term conclusion however as Andy argues in a previous comment.

However, Andy's argument above "Should the default namespace of a mock connection be auto-created?" is actually incorrect  in that in the case of interop as the default-namespace, the problem is that the other namespace defined in the MOF (root/cimv2) is never created which leads to the conclusion that ALL namespaces required for a mock environment must be created before the MOF defined for the script is compiled independent of what the user sets as default namespace or the MOF compler should be changed to attempt to create the namespace when the namespace #pragma is encountered in the MOF defined for the test script.

There is another possible extension in extending extending the compiler so that there was user control over whether the compiler actually created new namespaces since it is not clear that this is required for calls to an actual server.

**Comment by KSchopmeyer** [comment] 2021-12-02 18:57
NOTE: OpenPegasus "solved" the issues of the namespace pragma by never implementing the pragma.  They implemented the include pragma internally in the compiler, externalized all other pragma through a call and then only implemented "locale".

At least the command line call to OpenPegasus compiler compiles for a particular namespace and creates the  namespace if it does not already exist.

**Comment by KSchopmeyer** [comment] 2021-12-15 18:01
We discussed the issues and propose that if possible, we should modify the MOF compiler namespace pragma to  immediatly attempt to create a new namespace if  needed.   Action Karl


The default namespace general options should automatically create a name space if needed by the --default-namespace.

NOTE:  Using the --default-namespace when adding objects means that the target for those objects is that namespace. Thus if a user specifies interop as the default, compiles will be directed to that namespace unless the namespace pragma is used.  Whether we automatically create the default namespace in the mocker depends on whether you are using the --server  --name or --mock today.

There is a condrom here in that we need to decide how  much we should allow in creating the namespaces from the client. We should make it possible to create namespaces consistently from pywbem and let the server make the decision whether or not this is legal.  This means that we should try to create namespaces that do not exist from the --default-namespace whether it is a mock, --name, or --server when something is to be added to the target.

Note: We should use the add namespace rather than the pragma itself to create new namespaces since that makes adding from default namespace consistent with adding because MOF is compiled.

**Comment by andy-maier** [comment] 2021-12-18 04:51
Short summary of the desired behavior, according to the above:
* pragma namespace when compiling MOF should immediately create the namespace.
* The default namespace should be created in a deferred way, i.e. when an object is created.
The above should be the behavior regardless of the type of server (real or mock)

**Comment by KSchopmeyer** [comment] 2021-12-18 22:59
I thought that the rule would be that the pragma does not create the namespace but a create does create the namespace if it does not exist.  DISCUSSION

**Comment by andy-maier** [comment] 2021-12-22 09:11
An additional requirement is that namespace creation as a result of a pragma namespace in MOF needs a functioning Interop namespace.

**Comment by andy-maier** [comment] 2021-12-22 16:23
Conclusion of our meeting today was that Karl will review the test cases in the PR to figure out whether the current implementation is ok.

**Closed** 2022-01-02 12:13 UTC
Labels: area: code, resolution: fixed
