### ISSUE TITLE
Strange results when -o table used with EnumerateInstances on SFCB server

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#1016] opened 2021-07-11 03:33 UTC
We are getting different results from a pywbemcli request "instance enumerate" when the -o table form is used than when the default output format is used.

TODO: Add the detail data.

**Comment by andy-maier** [comment] 2021-07-11 12:20
Corrected server name to SFCB.

**Comment by andy-maier** [comment] 2021-07-12 19:50
Is this a duplicate of #1014 or a separate issue?

**Comment by andy-maier** [comment] 2021-07-17 15:06
We discussed this one. karl says it is in fact a duplicate of #1014. Closing it as a duplicate.

**Closed by andy-maier** 2021-07-17 15:06 UTC
Labels: resolution: duplicate
