### ISSUE TITLE
New "Exception ignored" and warning messages

### ISSUE THREAD

**Issue by KSchopmeyer** [pywbem/pywbemtools#883] opened 2021-01-26 17:17 UTC
Effective today I am gettingthe following when leaving interactive mode

Exception ignored in: <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 33414), raddr=('127.0.0.1', 5988)>
ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 33414), raddr=('127.0.0.1', 5988)>

pywbemcli, version 0.9.0.dev1
pywbem, version 1.2.0.dev1

Note sure why and not sure if this is just aberation but wanted to document for now.

This happens every time now when using OpenPegasus.

This is generally happening in any connection from pywbemcli on a ubuntu 1.04 python 3.6.8 client to either an openpegasus server on the same system or a local openpegasus container.

1. I happens only when using interactive mode.
2. It happens when communicating either with the local openpegasus or with openpegasus in a container.
3. It happens when you close the connection.
4. It does NOT happen when your are not in interactive mode
5. I saw it for the first time the day before this issues was filed.
6. It does not happen when pywbem_mock is the server

An example both interactive and cmd line modes
``` 

 ppp -n ophttp
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> class get blah
Error: CIMError: 6 (CIM_ERR_NOT_FOUND): CIM_ERR_NOT_FOUND: blah
pywbemcli>                                                                      
Exception ignored in: <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 36892), raddr=('127.0.0.1', 5988)>
ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 36892), raddr=('127.0.0.1', 5988)>

(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools(ks/#588-support-wbemsvrstats)$ ppp -n ophttp class get blah
Error: CIMError: 6 (CIM_ERR_NOT_FOUND): CIM_ERR_NOT_FOUND: blah
(pycli3) kschopmeyer@leonard:~/pywbem/pywbemtools(ks/#588-support-wbemsvrstats)$

**Comment by andy-maier** [comment] 2021-02-11 06:18
We are not closing the requests session in the pywbem library, and that is the likely root cause of this warning.

Probably the best solution is to fix the root cause by adding a close() method to pywbem.WBEMConnection that closes the requests session, and which we would then call in pywbemcli before leaving. I'll try that out.

**Comment by andy-maier** [comment] 2021-02-11 10:22
I have put up pywbem PR https://github.com/pywbem/pywbem/pull/2592 that adds a close() method to WBEMConnection, and pywbemtools PR #900 which calls that close() method when leaving interactive mode.

To try this out, you need the branches of both of these PRs installed.

@KSchopmeyer @cjrood Can you please try this out in your respective environments where you got the behavior described above, and post the results to this issue?

**Comment by andy-maier** [comment] 2021-02-11 11:52
In addition, I have created PR #899 to reproduce the behavior reported in this issue.

**Comment by KSchopmeyer** [comment] 2021-02-23 20:49
Tested with the current master of pywbemtools using python 3.6.9 and python 3.9.

The test was simply to executed a command in interactive mode against the container openpegasus

```

Python 3.9

(pycli39) kschopmeyer@leonard:~/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli(master)$ ppp -n docker1 --warh
Usage: pywbemcli [GENERAL-OPTIONS] COMMAND [ARGS] [COMMAND-OPTIONS]

Error: no such option: --warh
(pycli39) kschopmeyer@leonard:~/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli(master)$ ppp -n docker1 --warn
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> class get CIM_CIMDoor
Error: CIMError: 6 (CIM_ERR_NOT_FOUND): CIM_ERR_NOT_FOUND: CIM_CIMDoor
pywbemcli> class get CIM_CIMOMStatisticalData
   [Version ( "2.19.0" ),
    UMLPackagePath ( "CIM::Interop" ),
    Description (
       "CIM_CIMOMStatisticalData provides statistical data about the "
       "performance of the CIM Object Manager. Each object of this class "
       "provides elapsed time and size data for a particular type of CIM "
       "operation. All operations of that type, regardless of the CIM "
       "operations protocol being used, are accumulated in one object and "
       "covers the CIM operations issued by all clients of the Object Manager "
. . .
   uint32 ResetSelectedStats(
         [IN ( true ),
          Description (
             "Array of strings indicating which statistics to reset." )]
      string SelectedStatistics[]);

};
(pycli39) kschopmeyer@leonard:~/pywbem/pycli39/pywbemtools/pywbemtools/pywbemcli(master)$ python --version
Python 3.9.1

```

Python 3.6.8

```

(python36) kschopmeyer@leonard:~/pywbem/pycli36/pywbemtools(master)$ python --version
Python 3.6.9
(python36) kschopmeyer@leonard:~/pywbem/pycli36/pywbemtools(master)$ ppp -n docker1 --warn
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> class get CIM_CIMOMStatisticalData
   [Version ( "2.19.0" ),
    UMLPackagePath ( "CIM::Interop" ),
    Description (
       "CIM_CIMOMStatisticalData provides statistical data about the "
       "performance of the CIM Object Manager. Each object of this class "
 . . 
   uint32 ResetSelectedStats(
         [IN ( true ),
          Description (
             "Array of strings indicating which statistics to reset." )]
      string SelectedStatistics[]);

};

pywbemcli>                                                                      
sys:1: ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=2049, proto=6, laddr=('127.0.0.1', 48894), raddr=('127.0.0.1', 9988)>
(python36) kschopmeyer@leonard:~/pywbem/pycli36/pywbemtools(master)$

**Comment by KSchopmeyer** [comment] 2021-02-23 20:50
pip list python 3.6

```
Package        Version    Location
-------------- ---------- --------------------------------------------
asciitree      0.3.3
certifi        2020.12.5
chardet        4.0.0
click          7.1.2
click-repl     0.1.6
click-spinner  0.1.10
idna           2.10
mock           4.0.3
nocasedict     1.0.2
nocaselist     1.0.4
packaging      20.9
pip            21.0.1
ply            3.11
prompt-toolkit 3.0.16
pyparsing      2.4.7
pywbem         1.2.0.dev1
pywbemtools    0.9.0.dev1 /home/kschopmeyer/pywbem/pycli36/pywbemtools
PyYAML         5.4.1
requests       2.25.1
setuptools     53.0.0
six            1.15.0
tabulate       0.8.9
urllib3        1.26.3
wcwidth        0.2.5
wheel          0.36.2
yamlloader     0.5.5

**Comment by KSchopmeyer** [comment] 2021-02-23 20:51
pip list python 3.9.1

```

(pycli39) kschopmeyer@leonard:~/pywbem/pycli39/pywbemtools(master)$ python --version
Python 3.9.1
(pycli39) kschopmeyer@leonard:~/pywbem/pycli39/pywbemtools(master)$ pip list
Package                       Version    Location
----------------------------- ---------- --------------------------------------------
alabaster                     0.7.12
appdirs                       1.4.4
asciitree                     0.3.3
astroid                       2.3.3
attrs                         20.3.0
Babel                         2.9.0
bleach                        3.3.0
certifi                       2020.12.5
cffi                          1.14.5
chardet                       4.0.0
click                         7.1.2
click-repl                    0.1.6
click-spinner                 0.1.10
colorama                      0.4.4
coverage                      5.4
coveralls                     2.2.0
cryptography                  3.4.6
distlib                       0.3.1
distro                        1.5.0
docopt                        0.6.2
docutils                      0.16
dparse                        0.5.1
entrypoints                   0.3
fancycompleter                0.9.1
filelock                      3.0.12
flake8                        3.8.4
gitdb                         4.0.5
GitPython                     3.1.13
idna                          2.10
imagesize                     1.2.0
iniconfig                     1.1.1
isort                         4.3.21
jeepney                       0.6.0
Jinja2                        2.11.3
keyring                       22.0.1
lazy-object-proxy             1.4.3
MarkupSafe                    1.1.1
mccabe                        0.6.1
mock                          4.0.3
nocasedict                    1.0.2
nocaselist                    1.0.4
packaging                     20.9
pdbpp                         0.10.2
pip                           21.0.1
pkginfo                       1.7.0
pluggy                        0.13.1
ply                           3.11
prompt-toolkit                3.0.16
py                            1.10.0
pycodestyle                   2.6.0
pycparser                     2.20
pyflakes                      2.2.0
Pygments                      2.8.0
pylint                        2.4.4
pyparsing                     2.4.7
pyrepl                        0.9.0
pytest                        6.2.2
pytest-cov                    2.11.1
pytz                          2021.1
pywbem                        1.2.0.dev1
pywbemtools                   0.9.0.dev1 /home/kschopmeyer/pywbem/pycli39/pywbemtools
PyYAML                        5.4.1
readme-renderer               29.0
requests                      2.25.1
requests-toolbelt             0.9.1
rfc3986                       1.4.0
safety                        1.10.3
SecretStorage                 3.3.1
setuptools                    53.0.0
six                           1.15.0
smmap                         3.0.5
snowballstemmer               2.1.0
Sphinx                        3.5.1
sphinx-git                    11.0.0
sphinx-rtd-theme              0.5.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-fulltoc         1.2.0
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
tabulate                      0.8.9
toml                          0.10.2
tqdm                          4.57.0
twine                         3.3.0
urllib3                       1.26.3
virtualenv                    20.4.2
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.36.2
wmctrl                        0.3
wrapt                         1.11.2
yamlloader                    0.5.5

**Comment by andy-maier** [comment] 2021-02-24 03:54
I was now also able to reproduce the ResourceWarning on macOS.

In all cases, it was a freshly set up virtualenv and packages were installed with `make install`. With pywbemtools, I had the master branch checked out and pywbem was also installed from the master branch because the requirements file of pywbemtools currently pulls it from master.

The result is that the ResourceWarning appears with Python 3.7 and 3.8, but not with 3.9. Homebrew no longer installs Python 3.6 unfortunately.

Here are the details:

**Python 3.7**

```
(pywbemtools37) Andreass-MBP-2:pywbemtools maiera$ python --version
Python 3.7.9

(pywbemtools37) Andreass-MBP-2:pywbemtools maiera$ pip list
Package        Version    Location
-------------- ---------- ------------------------------------------------
asciitree      0.3.3
certifi        2020.12.5
chardet        4.0.0
click          7.1.2
click-repl     0.1.6
click-spinner  0.1.10
idna           2.10
mock           4.0.3
nocasedict     1.0.2
nocaselist     1.0.4
packaging      20.9
pip            21.0.1
ply            3.11
prompt-toolkit 3.0.16
pyparsing      2.4.7
pywbem         1.2.0.dev1
pywbemtools    0.9.0.dev1 /Users/maiera/PycharmProjects/pywbem/pywbemtools
PyYAML         5.4.1
requests       2.25.1
setuptools     53.0.0
six            1.15.0
tabulate       0.8.9
urllib3        1.26.3
wcwidth        0.2.5
wheel          0.36.2
yamlloader     0.5.5

(pywbemtools37) Andreass-MBP-2:pywbemtools maiera$ pywbemcli -n local --warn
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> class enumerate CIM_StatisticalData --no
CIM_BGPEndpointStatistics
...
pywbemcli>                                                                                                              
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 56131, 0, 0), raddr=('::1', 5989, 0, 0)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
(pywbemtools37) Andreass-MBP-2:pywbemtools maiera$ workon pywbemtools39
```

**Python 3.8**

```
(pywbemtools38) Andreass-MBP-2:pywbemtools maiera$ python --version
Python 3.8.7

(pywbemtools38) Andreass-MBP-2:pywbemtools maiera$ pip list
Package        Version    Location
-------------- ---------- ------------------------------------------------
asciitree      0.3.3
certifi        2020.12.5
chardet        4.0.0
click          7.1.2
click-repl     0.1.6
click-spinner  0.1.10
idna           2.10
mock           4.0.3
nocasedict     1.0.2
nocaselist     1.0.4
packaging      20.9
pip            21.0.1
ply            3.11
prompt-toolkit 3.0.16
pyparsing      2.4.7
pywbem         1.2.0.dev1
pywbemtools    0.9.0.dev1 /Users/maiera/PycharmProjects/pywbem/pywbemtools
PyYAML         5.4.1
requests       2.25.1
setuptools     53.0.0
six            1.15.0
tabulate       0.8.9
urllib3        1.26.3
wcwidth        0.2.5
wheel          0.36.2
yamlloader     0.5.5

(pywbemtools38) Andreass-MBP-2:pywbemtools maiera$ pywbemcli -n local --warn
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> class enumerate CIM_StatisticalData --no
CIM_BGPEndpointStatistics
...
pywbemcli>                                                                                                              
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=8, family=AddressFamily.AF_INET6, type=SocketKind.SOCK_STREAM, proto=0, laddr=('::1', 56125, 0, 0), raddr=('::1', 5989, 0, 0)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
(pywbemtools38) Andreass-MBP-2:pywbemtools maiera$ workon pywbemtools37
```

**Python 3.9**

```
(pywbemtools39) Andreass-MBP-2:pywbemtools maiera$ python --version
Python 3.9.1

(pywbemtools39) Andreass-MBP-2:pywbemtools maiera$ pip list
Package        Version    Location
-------------- ---------- ------------------------------------------------
asciitree      0.3.3
certifi        2020.12.5
chardet        4.0.0
click          7.1.2
click-repl     0.1.6
click-spinner  0.1.10
idna           2.10
mock           4.0.3
nocasedict     1.0.2
nocaselist     1.0.4
packaging      20.9
pip            21.0.1
ply            3.11
prompt-toolkit 3.0.16
pyparsing      2.4.7
pywbem         1.2.0.dev1
pywbemtools    0.9.0.dev1 /Users/maiera/PycharmProjects/pywbem/pywbemtools
PyYAML         5.4.1
requests       2.25.1
setuptools     53.0.0
six            1.15.0
tabulate       0.8.9
urllib3        1.26.3
wcwidth        0.2.5
wheel          0.36.2
yamlloader     0.5.5

(pywbemtools39) Andreass-MBP-2:pywbemtools maiera$ pywbemcli -n local --warn
Enter 'help' for help, <CTRL-D> or ':q' to exit pywbemcli or <CTRL-r> to search history, 
pywbemcli> class enumerate CIM_StatisticalData --no
CIM_BGPEndpointStatistics
...

pywbemcli>                                                                                                              
(pywbemtools39) Andreass-MBP-2:pywbemtools maiera$ 
```

**Comment by andy-maier** [comment] 2021-02-24 04:33
This issue https://github.com/boto/boto3/issues/454 provides pretty good insight into the unclosed socket problem. Nevertheless, closing the WBEMConnection is the right path to follow for us.

**Comment by andy-maier** [comment] 2021-02-24 04:36
I modified the error testcase added in PR #899 to add the `--warn` option and sure enough, the ResourceWarning is there. 

You can try that yourself by running `make end2endtest` as long as your target WBEM server is in a container. The container image name defaults to keyporttech/smi-server:0.1.2 and can be changed by setting the env var TEST_SERVER_IMAGE. See `make help` for details.

**Comment by andy-maier** [comment] 2021-02-24 05:11
Following up on the question why the interactive command does not produce the ResourceWarning on Python 3.9, I found out that it depends on how the interactive session is terminated. When using Control-D (on macOS) it does not show up, when using `:q` it does show up.

Summary for local macOS indicating whether the ResourceWarning was displayed:
```
OS      Python   make end2endtest   Interactive Ctrl-D   Interactive :q
-----------------------------------------------------------------------
macOS   3.7      yes                yes                  yes
macOS   3.8      yes                yes                  yes
macOS   3.9      yes                no(!)                yes
```

**Comment by andy-maier** [comment] 2021-02-28 07:56
One more tidbit:

Since Python 3.7, the ResourceWarning about the unclosed socket is followed by a ResourceWarning to enable tracemalloc:

```
sys:1: ResourceWarning: unclosed <ssl.SSLSocket fd=3, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 57952), raddr=('127.0.0.1', 15989)>
ResourceWarning: Enable tracemalloc to get the object allocation traceback
```

These have the same origin and the second one will go away once we fix the first one. See for example [this discussion](https://github.com/DataBiosphere/azul/issues/1825#issuecomment-637898338).

**Closed** 2021-03-06 15:55 UTC
Labels: area: code, resolution: fixed
